

CREATE TABLE `customer_order` (
  `OrderID` bigint NOT NULL COMMENT '入库ID',
  `CustomerID` bigint NOT NULL COMMENT '客户ID',
  `WarehouseID` bigint NOT NULL COMMENT '仓库ID',
  `ShopID` bigint DEFAULT NULL COMMENT '店铺ID',
  `OrderNo` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单号;后端生成',
  `ExtOrderNo` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '外部订单号',
  `ExtAdditionalInfo` varchar(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '外部附加信息',
  `OrderType` int NOT NULL COMMENT '订单类型',
  `OrderDate` datetime DEFAULT NULL COMMENT '订单日期',
  `ShopName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '店铺名称;界面填入',
  `ProductAmount` decimal(19,4) DEFAULT NULL COMMENT '产品金额;界面填入',
  `FreightAmount` decimal(19,4) DEFAULT NULL COMMENT '支付运费',
  `TaxeAmount` decimal(19,4) DEFAULT NULL COMMENT '支付税费',
  `DiscountAmount` decimal(19,4) DEFAULT NULL COMMENT '优惠金额',
  `TotalAmount` decimal(19,4) DEFAULT NULL COMMENT '总金额',
  `Status` int DEFAULT NULL COMMENT '订单状态',
  `RefReceiveID` bigint DEFAULT NULL COMMENT '收件人信息ID',
  `IsRefStockOut` int NOT NULL COMMENT '是否出库单',
  `RefStockOutIDs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '出库单ID',
  `ServiceFeeID` int DEFAULT NULL COMMENT '增值费用ID',
  `Creator` bigint NOT NULL COMMENT '创建人',
  `CreateTime` datetime NOT NULL COMMENT '创建时间',
  `Modifier` bigint DEFAULT NULL COMMENT '修改人',
  `ModifierTime` datetime DEFAULT NULL COMMENT '修改时间',
  `Channel` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单来源',
  `Region` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ThirdRefID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三方id（适用于订单到第三方平台，比如天聚、等其他平台）',
  `OrgOrderID` bigint DEFAULT NULL,
  `MarketplaceId` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ExtOrderNo2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ExtAdditionalInfo2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `HasBattery` bit(1) DEFAULT (0x00),
  `ECommercePostbackStatus` int DEFAULT NULL COMMENT '电商平台物流单号回传(0：否；1:是)',
  `IsPush` bit(1) DEFAULT NULL,
  `Vat` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Ioss` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Eori` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `LastShippingDate` datetime DEFAULT NULL,
  `LogisticsServiceName` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '物流服务名称',
  `SystemOrderType` int NOT NULL,
  `ForecastStatus` int DEFAULT NULL COMMENT '订单类型：（1: 交运订单  2：预报订单）',
  `TaskId` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '回传任务Id',
  PRIMARY KEY (`OrderID`) USING BTREE,
  KEY `ix_ExtOrderNo` (`ExtOrderNo`) USING BTREE,
  KEY `index_HasBattery` (`HasBattery`) USING BTREE,
  KEY `idx_orderno` (`OrderNo`) USING BTREE,
  KEY `idx_CreateTime` (`CreateTime`) USING BTREE,
  KEY `idx_customerid` (`CustomerID`) USING BTREE,
  KEY `index_SystemOrderType` (`SystemOrderType`) USING BTREE,
  KEY `Index_Status` (`Status`) USING BTREE,
  KEY `idx_whid_createtime_orderno` (`WarehouseID`,`CreateTime` DESC,`OrderNo` DESC) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='OMS客户订单表';
